# Generated by Django 4.1.7 on 2023-05-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_categories_category_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
