# Generated by Django 4.1.7 on 2023-05-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
